=== egibar/Draw/imagenes.dtd
<!ELEMENT imagenes(imagen)>
	<!ELEMENT imagen(link,solucion,usuario)>

		<!ELEMENT link (#PCDATA)>
		<!ELEMENT solucion (#PCDATA)>
		<!ELEMENT usuario (nombre, correo)>
			<!ELEMENT nombre (#PCDATA)>
			<!ELEMENT correo (#PCDATA)>

=== egibar/Draw/imagenes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE imagenes SYSTEM "imagenes.dtd">
<imagenes>	
	<imagen>
		<link>imagenes/casa.txt</link>
		<solucion>casa</solucion>
		<usuario>
			<nombre>Gorka</nombre>
			<correo>loque@gmail.com</correo>
		</usuario>
	</imagen>
<imagen><link>imagenes/raton.txt</link><solucion>raton</solucion><usuario><nombre>gorka</nombre><correo>prueba@gmall.com</correo></usuario></imagen>
</imagenes>
